// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pidar.Data;

#nullable disable

namespace Pidar.Migrations
{
    [DbContext(typeof(PidarDbContext))]
    [Migration("20250219061847_AddIdentityColumn")]
    partial class AddIdentityColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pidar.Models.Metadata", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Affiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeAtScanningExperimentS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeAtStartExperiment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiEnhancedAlgorithm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalgesicDose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalgesicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalgesicPlanToRelievePainSufferingAndDistress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalysisMethodAndDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalysisResultType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnesthesiaDose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnesthesiaDrugs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnesthesiaForImaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnesthesiaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Blinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodSampleVolume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodSampling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodSamplingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodTiming")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyTempuratureEtc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatalogueNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatalogueNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellInjectionRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellLines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChebiAnesthesia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChebiContrastAgentChemicalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChebiContrastAgentCommercialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChebiPharmaco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoPi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concentration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContrastAgentChemicalDrug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContrastAgentCommercialDrug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContrastAgentDose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContrastAgentOrRadioIsotopeOrChallengeWithGasMolecule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoregisteredImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Corrections")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfImagingFacility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryOfInstitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataUsedForAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatasetAccess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOfTheSurgicalProcedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DietaryIntervention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimensionExtents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiseaseModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayId")
                        .HasColumnType("int");

                    b.Property<string>("Doid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoseLoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugBatchSampleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugDose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuoDataUseModifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuoDataUsePermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuoInvestigation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentAndSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EuroBioImagingNode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Euthanasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExclusionCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiducialsUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOfView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileFormatOfResultFileCsvJsonTxtXlsx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodIntakeMeasured")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatCompression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequencyOfAdministration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequencyOfExperimentalMeasurements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequencyOfExperimentalProcedures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequencyOfImaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundingAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneticManipulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genotype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrantNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistologicalProcedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Histology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HousingRoom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAcquisitionParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageProcessingMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageReconstructionAlgorithm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageRegistrationAlgorithm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageScale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSmoothingOrFilteringAlgorithm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagingCoverage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagingFacility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagingModality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagingSubModality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagingTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmuneStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InclusionCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfectiousAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfectiousType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InjectionTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InjectionVolume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentSpecifics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentVendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LengthOfFixation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("License")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkToDataset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkToDataset1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelVersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedCellLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonitoringRegime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultiModalityImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfReagent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfReagentS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NcitAnatomy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NcitGene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NcitImaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NcitImagingSubmodality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NcitSpecies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NcitStrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfCells")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfGroups")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenAccess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganOrTissue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutcomeMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallNumberOfImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallSampleSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallScanLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperAuthors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperDoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperLinked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathogenInfectionInterventionAndControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharmacologicalDrug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharmacologicalProceduresInterventionAndControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PixelVoxelSizeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerCalculation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProceduresToKeepExperimenterBlind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProceduresToKeepTreatmentsBlind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provenance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QaQc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QcInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Radiation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Randomization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reagents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceToProtocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistryNumberOfAnimalAuthorization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedImagesAndRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespirationRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteOfAdministration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleSizeForEachGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteAndRouteOfInfection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteRouteOfAdministration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceOfAnimals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpatialAndTemporalAlignment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatisticalMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyDesignBackground")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudySubtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurgicalProceduresIncludingShamSurgery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetOrganTissue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimingOfCollection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimingOfExperimentalMeasurements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimingOfExperimentalProcedures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimingOfImaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimingOrFrequencyOfInfection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TissuesCollectedPostEuthanasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransformationMatrixOtherInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfGeneticModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypesOfGroups")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleOrCarrierSolutionFormulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationAndAuthentication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightAtEndExperiment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightAtStartExperiment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DatasetId");

                    b.ToTable("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
