// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pidar.Data;

#nullable disable

namespace Pidar.Migrations
{
    [DbContext(typeof(PidarDbContext))]
    [Migration("20251115032548_AddedReagentProcedures")]
    partial class AddedReagentProcedures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pidar.Models.Analyzed", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("AnalysisMethodAndDetails")
                        .HasColumnType("text");

                    b.Property<string>("AnalysisResultType")
                        .HasColumnType("text");

                    b.Property<string>("DataUsedForAnalysis")
                        .HasColumnType("text");

                    b.Property<string>("FileFormatOfResultFileCsvJsonTxtXlsx")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedYear")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("analyzed", "public");
                });

            modelBuilder.Entity("Pidar.Models.Dataset", b =>
                {
                    b.Property<int>("DatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dataset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DatasetId"));

                    b.Property<int>("DisplayId")
                        .HasColumnType("integer")
                        .HasColumnName("display_id");

                    b.HasKey("DatasetId")
                        .HasName("pk_dataset");

                    b.HasIndex("DisplayId")
                        .HasDatabaseName("ix_dataset_display_id");

                    b.ToTable("dataset", "public");
                });

            modelBuilder.Entity("Pidar.Models.DatasetInfo", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("CoPi")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("CountryOfImagingFacility")
                        .HasColumnType("text");

                    b.Property<string>("CountryOfInstitution")
                        .HasColumnType("text");

                    b.Property<string>("DatasetAccess")
                        .HasColumnType("text");

                    b.Property<string>("DuoDataUseModifier")
                        .HasColumnType("text");

                    b.Property<string>("DuoDataUsePermission")
                        .HasColumnType("text");

                    b.Property<string>("DuoInvestigation")
                        .HasColumnType("text");

                    b.Property<string>("EuroBioImagingNode")
                        .HasColumnType("text");

                    b.Property<string>("FunderId")
                        .HasColumnType("text");

                    b.Property<string>("Funding")
                        .HasColumnType("text");

                    b.Property<string>("FundingAgency")
                        .HasColumnType("text");

                    b.Property<string>("GrantNumber")
                        .HasColumnType("text");

                    b.Property<string>("ImagingFacility")
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .HasColumnType("text");

                    b.Property<string>("License")
                        .HasColumnType("text");

                    b.Property<string>("LicenseFile")
                        .HasColumnType("text");

                    b.Property<string>("LinkToDataset")
                        .HasColumnType("text");

                    b.Property<string>("Pi")
                        .HasColumnType("text");

                    b.Property<string>("PiOrchid")
                        .HasColumnType("text");

                    b.Property<string>("RorCodeOwner")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("dataset_info", "public");
                });

            modelBuilder.Entity("Pidar.Models.ImageAcquisition", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("Correction")
                        .HasColumnType("text");

                    b.Property<string>("ImageAcquisitionParameters")
                        .HasColumnType("text");

                    b.Property<string>("InstrumentSpecifics")
                        .HasColumnType("text");

                    b.Property<string>("InstrumentType")
                        .HasColumnType("text");

                    b.Property<string>("InstrumentVendor")
                        .HasColumnType("text");

                    b.Property<string>("QaQc")
                        .HasColumnType("text");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("image_acquisition", "public");
                });

            modelBuilder.Entity("Pidar.Models.ImageCorrelation", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("CoregisteredImages")
                        .HasColumnType("text");

                    b.Property<string>("FiducialsUsed")
                        .HasColumnType("text");

                    b.Property<string>("RelatedImagesAndRelationship")
                        .HasColumnType("text");

                    b.Property<string>("SpatialAndTemporalAlignment")
                        .HasColumnType("text");

                    b.Property<string>("TransformationMatrixOtherInfo")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("image_correlation", "public");
                });

            modelBuilder.Entity("Pidar.Models.ImageData", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("AiEnhanced")
                        .HasColumnType("text");

                    b.Property<string>("AiEnhancedAlgorithm")
                        .HasColumnType("text");

                    b.Property<string>("Corrections")
                        .HasColumnType("text");

                    b.Property<string>("DimensionExtents")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<string>("FieldOfView")
                        .HasColumnType("text");

                    b.Property<string>("FormatCompression")
                        .HasColumnType("text");

                    b.Property<string>("ImageAttenuationCorrection")
                        .HasColumnType("text");

                    b.Property<string>("ImageProcessingMethods")
                        .HasColumnType("text");

                    b.Property<string>("ImageReconstructionAlgorithm")
                        .HasColumnType("text");

                    b.Property<string>("ImageRegistrationAlgorithm")
                        .HasColumnType("text");

                    b.Property<string>("ImageScale")
                        .HasColumnType("text");

                    b.Property<string>("ImageSmoothingOrFilteringAlgorithm")
                        .HasColumnType("text");

                    b.Property<string>("ImageType")
                        .HasColumnType("text");

                    b.Property<string>("OverallNumberOfImages")
                        .HasColumnType("text");

                    b.Property<string>("PixelVoxelSizeDescription")
                        .HasColumnType("text");

                    b.Property<string>("QcInfo")
                        .HasColumnType("text");

                    b.Property<string>("QualityControl")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationAlgorithms")
                        .HasColumnType("text");

                    b.Property<string>("SizeDescription")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("image_data", "public");
                });

            modelBuilder.Entity("Pidar.Models.InVivo", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("AgeAtScanningExperimentS")
                        .HasColumnType("text");

                    b.Property<string>("AgeAtStartExperiment")
                        .HasColumnType("text");

                    b.Property<string>("AnimalCondition")
                        .HasColumnType("text");

                    b.Property<string>("Blinding")
                        .HasColumnType("text");

                    b.Property<string>("DiseaseModel")
                        .HasColumnType("text");

                    b.Property<string>("ExclusionCriteria")
                        .HasColumnType("text");

                    b.Property<string>("Gene")
                        .HasColumnType("text");

                    b.Property<string>("GeneticManipulation")
                        .HasColumnType("text");

                    b.Property<string>("Genotype")
                        .HasColumnType("text");

                    b.Property<string>("ImmuneStatus")
                        .HasColumnType("text");

                    b.Property<string>("InclusionCriteria")
                        .HasColumnType("text");

                    b.Property<string>("NumberOfGroups")
                        .HasColumnType("text");

                    b.Property<string>("OrganOrTissue")
                        .HasColumnType("text");

                    b.Property<string>("OutcomeMeasures")
                        .HasColumnType("text");

                    b.Property<string>("OverallSampleSize")
                        .HasColumnType("text");

                    b.Property<string>("PowerCalculation")
                        .HasColumnType("text");

                    b.Property<string>("ProceduresToKeepExperimenterBlind")
                        .HasColumnType("text");

                    b.Property<string>("ProceduresToKeepTreatmentsBlind")
                        .HasColumnType("text");

                    b.Property<string>("Randomization")
                        .HasColumnType("text");

                    b.Property<string>("RegistryNumberOfAnimalAuthorization")
                        .HasColumnType("text");

                    b.Property<string>("SampleSizeForEachGroup")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("SourceOfAnimals")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .HasColumnType("text");

                    b.Property<string>("StatisticalMethods")
                        .HasColumnType("text");

                    b.Property<string>("Strain")
                        .HasColumnType("text");

                    b.Property<string>("TypesOfGroups")
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.Property<string>("WeightAtEndExperiment")
                        .HasColumnType("text");

                    b.Property<string>("WeightAtStartExperiment")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("in_vivo", "public");
                });

            modelBuilder.Entity("Pidar.Models.Ontology", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("ChebiAnesthesia")
                        .HasColumnType("text");

                    b.Property<string>("ChebiContrastAgentChemicalName")
                        .HasColumnType("text");

                    b.Property<string>("ChebiContrastAgentCommercialName")
                        .HasColumnType("text");

                    b.Property<string>("ChebiPharmaco")
                        .HasColumnType("text");

                    b.Property<string>("Clo")
                        .HasColumnType("text");

                    b.Property<string>("Doid")
                        .HasColumnType("text");

                    b.Property<string>("NcitAnatomy")
                        .HasColumnType("text");

                    b.Property<string>("NcitGene")
                        .HasColumnType("text");

                    b.Property<string>("NcitImaging")
                        .HasColumnType("text");

                    b.Property<string>("NcitImagingSubmodality")
                        .HasColumnType("text");

                    b.Property<string>("NcitSpecies")
                        .HasColumnType("text");

                    b.Property<string>("NcitStrain")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("ontology", "public");
                });

            modelBuilder.Entity("Pidar.Models.Procedures", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("AnalgesicDose")
                        .HasColumnType("text");

                    b.Property<string>("AnalgesicName")
                        .HasColumnType("text");

                    b.Property<string>("AnalgesicPlanToRelievePainSufferingAndDistress")
                        .HasColumnType("text");

                    b.Property<string>("AnesthesiaDose")
                        .HasColumnType("text");

                    b.Property<string>("AnesthesiaDrugs")
                        .HasColumnType("text");

                    b.Property<string>("AnesthesiaForImaging")
                        .HasColumnType("text");

                    b.Property<string>("AnesthesiaType")
                        .HasColumnType("text");

                    b.Property<string>("BloodCollectionTiming")
                        .HasColumnType("text");

                    b.Property<string>("BloodSampleVolume")
                        .HasColumnType("text");

                    b.Property<string>("BloodSampling")
                        .HasColumnType("text");

                    b.Property<string>("BloodSamplingMethod")
                        .HasColumnType("text");

                    b.Property<string>("BloodTiming")
                        .HasColumnType("text");

                    b.Property<string>("BodyTempuratureEtc")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueNumber")
                        .HasColumnType("text");

                    b.Property<string>("CatalogueNumbers")
                        .HasColumnType("text");

                    b.Property<string>("CellCultureMedium")
                        .HasColumnType("text");

                    b.Property<string>("CellInjectionProcedure")
                        .HasColumnType("text");

                    b.Property<string>("CellInjectionRoute")
                        .HasColumnType("text");

                    b.Property<string>("CellLine")
                        .HasColumnType("text");

                    b.Property<string>("CellLines")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("Concentration")
                        .HasColumnType("text");

                    b.Property<string>("ContrastAgentChemicalDrug")
                        .HasColumnType("text");

                    b.Property<string>("ContrastAgentCommercialDrug")
                        .HasColumnType("text");

                    b.Property<string>("ContrastAgentDose")
                        .HasColumnType("text");

                    b.Property<string>("ContrastAgentOrRadioIsotopeOrChallengeWithGasMolecule")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionOfTheSurgicalProcedure")
                        .HasColumnType("text");

                    b.Property<string>("DietaryIntervention")
                        .HasColumnType("text");

                    b.Property<string>("DoseLoad")
                        .HasColumnType("text");

                    b.Property<string>("DrugDose")
                        .HasColumnType("text");

                    b.Property<string>("DrugOrBatchSampleNumber")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("EquipmentAndSoftware")
                        .HasColumnType("text");

                    b.Property<string>("Euthanasia")
                        .HasColumnType("text");

                    b.Property<string>("FoodIntakeMeasured")
                        .HasColumnType("text");

                    b.Property<string>("Formulation")
                        .HasColumnType("text");

                    b.Property<string>("FrequencyOfAdministration")
                        .HasColumnType("text");

                    b.Property<string>("FrequencyOfExperimentalMeasurements")
                        .HasColumnType("text");

                    b.Property<string>("FrequencyOfExperimentalProcedures")
                        .HasColumnType("text");

                    b.Property<string>("FrequencyOfImaging")
                        .HasColumnType("text");

                    b.Property<string>("GeneModified")
                        .HasColumnType("text");

                    b.Property<string>("HistologicalProcedure")
                        .HasColumnType("text");

                    b.Property<string>("Histology")
                        .HasColumnType("text");

                    b.Property<string>("HousingRoom")
                        .HasColumnType("text");

                    b.Property<string>("Imaging")
                        .HasColumnType("text");

                    b.Property<string>("InfectiousAgent")
                        .HasColumnType("text");

                    b.Property<string>("InfectiousType")
                        .HasColumnType("text");

                    b.Property<string>("InjectionTime")
                        .HasColumnType("text");

                    b.Property<string>("InjectionVolume")
                        .HasColumnType("text");

                    b.Property<string>("LengthOfFixation")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("ModelVersionNumber")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedCellLine")
                        .HasColumnType("text");

                    b.Property<string>("MonitoringRegime")
                        .HasColumnType("text");

                    b.Property<string>("NameOfReagent")
                        .HasColumnType("text");

                    b.Property<string>("NameOfReagentS")
                        .HasColumnType("text");

                    b.Property<string>("NumberOfCells")
                        .HasColumnType("text");

                    b.Property<string>("OverallScanLength")
                        .HasColumnType("text");

                    b.Property<string>("PathogenInfectionInterventionAndControl")
                        .HasColumnType("text");

                    b.Property<string>("PerfusionMethod")
                        .HasColumnType("text");

                    b.Property<string>("PharmacologicalDrug")
                        .HasColumnType("text");

                    b.Property<string>("PharmacologicalProceduresInterventionAndControl")
                        .HasColumnType("text");

                    b.Property<string>("Provenance")
                        .HasColumnType("text");

                    b.Property<string>("Reagents")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceToProtocol")
                        .HasColumnType("text");

                    b.Property<string>("RespirationRate")
                        .HasColumnType("text");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<string>("RouteOfAdministration")
                        .HasColumnType("text");

                    b.Property<string>("SiteAndRouteOfInfection")
                        .HasColumnType("text");

                    b.Property<string>("SiteOrRouteOfAdministration")
                        .HasColumnType("text");

                    b.Property<string>("SpecimenThickness")
                        .HasColumnType("text");

                    b.Property<string>("SurgicalProceduresIncludingShamSurgery")
                        .HasColumnType("text");

                    b.Property<string>("TargetOrganTissue")
                        .HasColumnType("text");

                    b.Property<string>("TimingOfCollection")
                        .HasColumnType("text");

                    b.Property<string>("TimingOfExperimentalMeasurements")
                        .HasColumnType("text");

                    b.Property<string>("TimingOfExperimentalProcedures")
                        .HasColumnType("text");

                    b.Property<string>("TimingOfImaging")
                        .HasColumnType("text");

                    b.Property<string>("TimingOrFrequencyOfInfection")
                        .HasColumnType("text");

                    b.Property<string>("TissueDescription")
                        .HasColumnType("text");

                    b.Property<string>("TissuePerfused")
                        .HasColumnType("text");

                    b.Property<string>("TissuesCollectedPostEuthanasia")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfGeneticModification")
                        .HasColumnType("text");

                    b.Property<string>("Vehicle")
                        .HasColumnType("text");

                    b.Property<string>("VehicleOrCarrierSolutionFormulation")
                        .HasColumnType("text");

                    b.Property<string>("VerificationAndAuthentication")
                        .HasColumnType("text");

                    b.Property<string>("VirusLabelledOrModified")
                        .HasColumnType("text");

                    b.Property<string>("Volume")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("procedures", "public");
                });

            modelBuilder.Entity("Pidar.Models.Publication", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("Affiliation")
                        .HasColumnType("text");

                    b.Property<string>("OpenAccess")
                        .HasColumnType("text");

                    b.Property<string>("PaperAuthors")
                        .HasColumnType("text");

                    b.Property<string>("PaperDoi")
                        .HasColumnType("text");

                    b.Property<string>("PaperJournal")
                        .HasColumnType("text");

                    b.Property<string>("PaperLinked")
                        .HasColumnType("text");

                    b.Property<string>("PaperTitle")
                        .HasColumnType("text");

                    b.Property<string>("PaperYear")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("publication", "public");
                });

            modelBuilder.Entity("Pidar.Models.StudyComponent", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagingCoverage")
                        .HasColumnType("text");

                    b.Property<string>("ImagingModality")
                        .HasColumnType("text");

                    b.Property<string>("ImagingSubModality")
                        .HasColumnType("text");

                    b.Property<string>("ImagingTarget")
                        .HasColumnType("text");

                    b.Property<string>("MultiModalityImages")
                        .HasColumnType("text");

                    b.Property<string>("Radiation")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("study_component", "public");
                });

            modelBuilder.Entity("Pidar.Models.StudyDesign", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("integer");

                    b.Property<string>("StudyDescription")
                        .HasColumnType("text");

                    b.Property<string>("StudyDesignBackground")
                        .HasColumnType("text");

                    b.Property<string>("StudySubtype")
                        .HasColumnType("text");

                    b.Property<string>("StudyType")
                        .HasColumnType("text");

                    b.HasKey("DatasetId");

                    b.ToTable("study_design", "public");
                });

            modelBuilder.Entity("Pidar.Models.Analyzed", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("Analyzed")
                        .HasForeignKey("Pidar.Models.Analyzed", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.DatasetInfo", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("DatasetInfo")
                        .HasForeignKey("Pidar.Models.DatasetInfo", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.ImageAcquisition", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("ImageAcquisition")
                        .HasForeignKey("Pidar.Models.ImageAcquisition", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.ImageCorrelation", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("ImageCorrelation")
                        .HasForeignKey("Pidar.Models.ImageCorrelation", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.ImageData", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("ImageData")
                        .HasForeignKey("Pidar.Models.ImageData", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.InVivo", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("InVivo")
                        .HasForeignKey("Pidar.Models.InVivo", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.Ontology", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("Ontology")
                        .HasForeignKey("Pidar.Models.Ontology", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.Procedures", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("Procedures")
                        .HasForeignKey("Pidar.Models.Procedures", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.Publication", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("Publication")
                        .HasForeignKey("Pidar.Models.Publication", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.StudyComponent", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("StudyComponent")
                        .HasForeignKey("Pidar.Models.StudyComponent", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.StudyDesign", b =>
                {
                    b.HasOne("Pidar.Models.Dataset", null)
                        .WithOne("StudyDesign")
                        .HasForeignKey("Pidar.Models.StudyDesign", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pidar.Models.Dataset", b =>
                {
                    b.Navigation("Analyzed");

                    b.Navigation("DatasetInfo");

                    b.Navigation("ImageAcquisition");

                    b.Navigation("ImageCorrelation");

                    b.Navigation("ImageData");

                    b.Navigation("InVivo");

                    b.Navigation("Ontology");

                    b.Navigation("Procedures");

                    b.Navigation("Publication");

                    b.Navigation("StudyComponent");

                    b.Navigation("StudyDesign");
                });
#pragma warning restore 612, 618
        }
    }
}
